# This file is a template, and might need editing before it works on your project.
# Unofficial language image. Look for the different tagged releases at:
# https://hub.docker.com/r/scorpil/rust/tags/
image: "qinsoon/ubuntu-zebu-test:v0.1"

# Optional: Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
#services:
#  - mysql:latest
#  - redis:latest
#  - postgres:latest

# Optional: Install a C compiler, cmake and git into the container.
# You will often need this when you (or any of your dependencies) depends on C code.
#before_script:
#- apt-get update -yqq
#- apt-get install -yqq --no-install-recommends build-essential

# Use cargo to test the project
cache:
  key: "$CI_BUILD_STAGE/$CI_BUILD_REF_NAME"
  paths:
    - .cargo/registry/cache
    - .cargo/registry/index
    - target
    - Cargo.lock

before_script:
  - time CARGO_HOME=.cargo RUST_BACKTRACE=1 CC=clang cargo test --no-run

test:cargo:api:
  stage: test
  script:
    - CARGO_HOME=.cargo RUST_BACKTRACE=1 RUST_TEST_THREADS=1 CC=clang cargo test test_api 2> /dev/null

test:cargo:ir:
  stage: test
  script:
    - CARGO_HOME=.cargo RUST_BACKTRACE=1 RUST_TEST_THREADS=1 CC=clang cargo test test_ir 2> /dev/null

test:cargo:compiler:
  stage: test
  script:
    - CARGO_HOME=.cargo RUST_BACKTRACE=1 RUST_TEST_THREADS=1 CC=clang cargo test test_compiler 2> /dev/null

test:cargo:runtime:
  stage: test
  script:
    - CARGO_HOME=.cargo RUST_BACKTRACE=1 RUST_TEST_THREADS=1 CC=clang cargo test test_runtime 2> /dev/null

testjit:milestones:
  stage: test
  script:
    - RUST_BACKTRACE=1 pytest tests/test_jit/test_milestones.py -v

testjit:binops:
  stage: test
  script:
    - RUST_BACKTRACE=1 pytest tests/test_jit/test_binops.py -v

testjit:cmpops:
  stage: test
  script:
    - RUST_BACKTRACE=1 pytest tests/test_jit/test_cmpops.py -v

testjit:controlflow:
  stage: test
  script:
    - cd tests/test_jit
    - RUST_BACKTRACE=1 pytest test_controlflow.py -v

testjit:convops:
  stage: test
  script:
    - RUST_BACKTRACE=1 pytest tests/test_jit/test_convops.py -v

testjit:double:
  stage: test
  script:
    - RUST_BACKTRACE=1 pytest tests/test_jit/test_double.py -v

testjit:memops:
  stage: test
  script:
    - RUST_BACKTRACE=1 pytest tests/test_jit/test_memops.py -v

testjit:milestones:
  stage: test
  script:
    - RUST_BACKTRACE=1 pytest tests/test_jit/test_milestones.py -v

testjit:otherops:
  stage: test
  script:
    - RUST_BACKTRACE=1 pytest tests/test_jit/test_otherops.py -v

testjit:rpython:
  stage: test
  script:
    - git clone https://gitlab.anu.edu.au/mu/mu-client-pypy.git tests/test_jit/mu-client-pypy
    - cd tests/test_jit/mu-client-pypy
    - git checkout mu-rewrite-zebu-no-binop-with-flag
    - cd rpython/translator/mu/rpyc; make
    - cd $CI_PROJECT_DIR/tests/test_jit
    - RUST_BACKTRACE=1 LD_LIBRARY_PATH=. PYTHONPATH=mu-client-pypy MU_RUST=$CI_PROJECT_DIR pytest test_rpython*.py -v
  cache:
    key: "$CI_BUILD_STAGE/$CI_BUILD_REF_NAME"
    paths:
      - .cargo/registry/cache
      - .cargo/registry/index
      - target
      - Cargo.lock
      - tests/test_jit/mu-client-pypy
