# This file is a template, and might need editing before it works on your project.
# Unofficial language image. Look for the different tagged releases at:
# https://hub.docker.com/r/scorpil/rust/tags/
image: "qinsoon/ubuntu-zebu-test:v0.1"

# Optional: Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
#services:
#  - mysql:latest
#  - redis:latest
#  - postgres:latest

# Optional: Install a C compiler, cmake and git into the container.
# You will often need this when you (or any of your dependencies) depends on C code.
#before_script:
#- apt-get update -yqq
#- apt-get install -yqq --no-install-recommends build-essential

# Use cargo to test the project
test:cargo:
  script:
  - rustc --version && cargo --version      # Print version info for debugging
  - RUSTFLAGS=-Zincremental=target/incr-cache RUST_BACKTRACE=1 RUST_TEST_THREADS=1 CC=clang cargo test

testjit:milestones:
  script:
  - cd tests/test_jit
  - MU_RUST=$CI_PROJ_DIR pytest test_milestones.py

testjit:binops:
  script:
  - cd tests/test_jit
  - MU_RUST=$CI_PROJ_DIR pytest test_binops.py

testjit:cmpops:
  script:
  - cd tests/test_jit
  - MU_RUST=$CI_PROJ_DIR pytest test_cmpops.py
