[package]

name = "mu"
version = "0.0.1"
authors = [ "Your name <you@example.com>" ]
build = "build.rs"

[dependencies.immix_rust]
path = "gc"

[build-dependencies.gcc]
git = "https://github.com/alexcrichton/gcc-rs"

[dependencies]
lazy_static = "0.1.15"
log = "0.3.5"
simple_logger = "0.4.0"
nalgebra = "0.8.2"
linked-hash-map = "0.0.10"
hprof = "0.1.3"
memmap = "0.4.0"
memsec = "0.1.9"
rustc-serialize = "*"