unstable_features = true
condense_wildcard_suffixes = true
imports_indent = "Block"
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
trailing_comma = "Never"
max_width = 120
