[package]
name = "ast"
version = "0.0.1"
authors = ["qinsoon <qinsoon@gmail.com>"]

[lib]
crate-type = ["rlib"]

[dependencies]
utils = {path = "../utils"}
lazy_static = "0.1.15"
log = "0.3.5"
simple_logger = "0.4.0"
rustc-serialize = "*"